### ISSUE TITLE
headtracking

### ISSUE THREAD

**Issue by Eignar17** [ethus3h/compiz-plugins-community#5]
possibly add plugin

http://forum.compiz.org/viewtopic.php?f=89&t=9746&hilit=Headtracking

possibly add plugin:
http://forum.compiz.org/download/file.php?id=1589
 
patch facedetect:
http://forum.compiz.org/download/file.php?id=1710

I want view your opinion for plugin

**Comment by ethus3h** [comment]
Sorry I took so long to get back regarding this. The plugin is now in and compiles/installs correctly, although it crashed when I tried to use the Webcam feature. I don't have a Wii controller to test that part of it with. Anyway, at least it can get shipped now and hopefully some one who wants it will know how to fix it!

I did have to tweak a couple of things in the facedetect code to adjust for OpenCV API changes: set the Webcam to always use camera at index 0, and fill in a dummy value for maximum size; it refused to build otherwise: https://github.com/ethus3h/compiz-plugins-community/commit/a63b73358837479ad9960d3ad31e5bb4fc4a8736

**Comment by ethus3h** [comment]
(Maybe it doesn't like that dummy maximum size value? I haven't tried to debug the crash at all. I don't know what would go in for a maximum size anyway.)

**Comment by ethus3h** [comment]
I filed a separate issue for the crash at #7.

**Comment by Eignar17** [comment]
@ethus3h is problem in to OpenCV or plugin tall project OpenCV view bug
